version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test: # Construction et execution des tests pour validation
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Set environment variables
          command: echo "SECRET_KEY=$SECRET_KEY" >> $BASH_ENV
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_docker_image:  # Construction de l'image et push vers Docker Hub
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker: # Use remote Docker executor !
          version: 20.10.14
          docker_layer_caching: true # Enable Docker layer caching
      - run:
          name: Build Docker image
          command: docker build --build-arg SECRET_KEY=$SECRET_KEY -t qmolieres/oc-lettings:latest .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push qmolieres/oc-lettings:latest 

#    deploy:
#      executor: python/default
#      steps:
#        - attach_workspace:
#            at: ~/project
#        - heroku/deploy-via-git:
#            force: true

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - build_docker_image
#      - deploy:
#          requires:
#            - build_and_test # deploiment seulement si build_and_test est passé
#          filters:
#            branches:
#              only: main

